config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"

  resources :sessions do
    get '/callback', to: 'sessions#callback',on: :collection
    get '/media', to: 'sessions#media',on: :collection
    get '/user', to: 'sessions#user',on: :collection
  end

  get '/instagram/callback', to: 'instagram#callback'
  post '/instagram/access', to: 'instagram#access'
  get '/instagram', to: 'instagram#index'
  get '/instagram/user_info', to: 'instagram#user_info'
  get '/instagram/user_insights', to: 'instagram#user_insights'
  get '/instagram/media_insights', to: 'instagram#media_insights'

  resources :tiktok, only: [:index] do
    get :research_token, on: :collection
    get :research_api, on: :collection
  end
  get '/auth/tiktok/login', to: 'tiktok#tiktok_auth'
  get '/auth/callback', to: 'tiktok#callback'


  resources :subscriptions, only: [:index, :create] do
    post :create_payment, on: :collection
    get :new_card, on: :collection
    post :create_card, on: :collection
    get :remove_cards, on: :collection
    get :list_payments, on: :collection
  end

  namespace :payment_gateway, path: 'pg' do
    resources :payment, only: [:create] do
      post :create_sub, on: :collection
    end
  end

  resources :culqi, only: [:index, :create]
end

app/controllers/subscriptions_controller.rb
require 'mercadopago'
class SubscriptionsController < ApplicationController
  def index
    # listar tarjetas
    sdk = Mercadopago::SDK.new('TEST-1973919203979809-020319-259229814a2fe088fed016868af2588b-1665928197')
    cards_response = sdk.card.list('1666102147-Vr6jz04Pk43GS7')
    cards = cards_response[:response]
    # @cards = cards.map do |card|
    #   {
    #     id: card["id"],
    #     last_four_digits: card["last_four_digits"],
    #     payment_method: card["payment_method"]["name"]
    #   }
    # end
    # @cards.map! { |hash| OpenStruct.new(hash) }

    @cards = cards.map do |card|
      {
        "id": card["id"],
        "last_four_digits": card["last_four_digits"],
        "payment_method": { name: card["payment_method"]["name"] }
      }
    end
  end

  def new_card
  end

  def create_card
    sdk = Mercadopago::SDK.new('TEST-1973919203979809-020319-259229814a2fe088fed016868af2588b-1665928197')
    card_request = {
      token: params[:token]
    }
    card_response = sdk.card.create('1666102147-Vr6jz04Pk43GS7', card_request)
    card = card_response[:response]

    render json: { message: 'Card created successfully!' }
  end

  def remove_cards
    sdk = Mercadopago::SDK.new('TEST-1973919203979809-020319-259229814a2fe088fed016868af2588b-1665928197')
    cards_response = sdk.card.list('1666102147-Vr6jz04Pk43GS7')
    cards = cards_response[:response]

    cards.each do |card|
      sdk.card.delete('1666102147-Vr6jz04Pk43GS7', card['id'])
    end

    redirect_to subscriptions_path
  end

  def plans
    response = HTTParty.get(
      'https://api.mercadopago.com/preapproval_plan/search',
      headers: {
        'Content-Type' => 'application/json',
        'Authorization' => 'Bearer TEST-1973919203979809-020319-259229814a2fe088fed016868af2588b-1665928197'
      }
    )
    puts response.body
    @plans = JSON.parse(response.body, symbolize_names: true)
    @plans = @plans[:results]
  end

  def list_payments
    url = 'https://api.mercadopago.com/v1/payments/search'
    headers = {
      'Content-Type' => 'application/json',
      'Authorization' => 'Bearer TEST-1973919203979809-020319-259229814a2fe088fed016868af2588b-1665928197'
    }

    response = HTTParty.get(url, headers: headers)
    @payments = JSON.parse(response.body, symbolize_names: true)
    @payments = @payments[:results]
    @payments = @payments.map do |pay|
      {
        "id": pay[:id],
        # "card": pay[:card]
      }
    end
    render json: @payments
  end

  # create payment and subscription
  def create
    # binding.pry
    # url = 'https://api.mercadopago.com/preapproval'
    # headers = {
    #   'Content-Type' => 'application/json',
    #   'Authorization' => 'Bearer TEST-1973919203979809-020319-259229814a2fe088fed016868af2588b-1665928197'
    # }
    # body = {
    #   back_url: 'https://www.mercadopago.com.pe',
    #   card_token_id: params['token'],
    #   external_reference: Time.now.to_i.to_s,
    #   payer_email: 'test_payer_01@testuser.com',
    #   preapproval_plan_id: '2c9380848d698da5018d7c5b7cbe0d7c',
    #   reason: 'example subscription',
    #   status: 'authorized'
    # }.to_json

    # response = HTTParty.post(url, headers: headers, body: body)
    # puts params[:token]
    # puts response
    # redirect_to subscriptions_path

    sdk = Mercadopago::SDK.new('TEST-1973919203979809-020319-259229814a2fe088fed016868af2588b-1665928197')
    payment_request = {
      token: params[:token],
      installments: 1,
      transaction_amount: 100,
      payer: {
        type: 'customer',
        id: '1666102147-Vr6jz04Pk43GS7'
      }
    }

    payment_response = sdk.payment.create(payment_request)
    payment = payment_response[:response]

    if payment['status'] == 'approved'
      puts "Pago aprobado!"
      puts payment
      flash[:notice] = "Pago aprobado! pago id: #{payment['id']}, status: #{payment['status']}"
      redirect_to subscriptions_path
    else
      puts "Pago rechazado!"
      puts payment
      flash[:notice] = "Your notice message here"
      redirect_to subscriptions_path
    end
  end

  def create_payment
    sdk = Mercadopago::SDK.new('TEST-1973919203979809-020319-259229814a2fe088fed016868af2588b-1665928197')
    binding.pry
    # # crear customer
    # customer_request = {
    #   email: 'test_payer_02@testuser.com'
    # }
    # customer_response = sdk.customer.create(customer_request)
    # customer = customer_response[:response]
    # puts customer

    # # crear tarjeta
    # card_request = {
    #   token: params[:token]
    # }
    # card_response = sdk.card.create(customer['id'], card_request)
    # card = card_response[:response]
    # puts card

    # # crear payment
    payment_request = {
      token: params[:token],
      installments: 3,
      transaction_amount: 100,
      payer: {
        type: 'customer',
        id: '1666102147-Vr6jz04Pk43GS7'
      }
    }
    payment_response = sdk.payment.create(payment_request)
    payment = payment_response[:response]
    # puts payment
  end
end


# curl -X GET \
# 'https://api.mercadopago.com/v1/payments/1316939502'\
#   -H 'Content-Type: application/json' \
#   -H 'Authorization: Bearer TEST-1973919203979809-020319-259229814a2fe088fed016868af2588b-1665928197' \


# curl -X GET \
#   'https://api.mercadopago.com/v1/payments/search'\
#     -H 'Content-Type: application/json' \
#     -H 'Authorization: Bearer TEST-1973919203979809-020319-259229814a2fe088fed016868af2588b-1665928197' \

app/views/subscriptions/_index.html.erb
<% @cards.each do |card| %>
  <label class="card-label">
    <%= radio_button_tag 'selected_card', card.id, false, class: "card-radio" %>
    <span class="radio-button-style"></span>
    <%= "#{card.payment_method} finalizada en #{card.last_four_digits}" %>
  </label>
<% end %>
<%= link_to 'Agregar método de pago', new_card_subscriptions_path, class: "add-payment-method-button" %>





<style>
.card-label {
  display: block;
  margin-bottom: 10px;
  position: relative;
}

.card-radio {
  /* Hide default radio button */
  opacity: 0;
  position: absolute;
  left: 0;
}

.radio-button-style {
  /* Define styles for the custom radio button appearance */
  display: inline-block;
  width: 10px; /* Adjust width */
  height: 10px; /* Adjust height */
  border: 2px solid #999;
  border-radius: 50%;
  margin-right: 4px;
  position: relative;
}

.radio-button-style:before {
  content: '';
  display: block;
  width: 6px; /* Adjust width */
  height: 6px; /* Adjust height */
  background-color: #999;
  border-radius: 50%;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%) scale(0);
  transition: transform 0.2s ease-out;
}

.card-radio:checked + .radio-button-style:before {
  transform: translate(-50%, -50%) scale(1);
}

.add-payment-method-button {
  /* Define styles for the "Agregar método de pago" link */
  display: inline-block;
  padding: 8px 16px;
  background-color: #007bff;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
}

.add-payment-method-button:hover {
  background-color: #0056b3;
}

</style>

app/views/subscriptions/index.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>


<form id="form-checkout" method="POST" action="/subscriptions">
  <select type="text" id="form-checkout__cardId"></select>
  <div id="form-checkout__securityCode-container" class="container"></div>
  <input name="token" id="token" hidden>
  <button>Enviar</button>
</form>

<%= link_to 'Agregar método de pago', new_card_subscriptions_path, class: "add-payment-method-button" %>
<%= link_to 'Eliminar tarjetas', remove_cards_subscriptions_path, disabled: true, onclick: "this.disabled=true;", class: "remove-button" %>
<%= link_to 'listar pagos', list_payments_subscriptions_path, class: "list-button" %>

<style>
.add-payment-method-button {
  display: inline-block;
  padding: 4px 8px;
  background-color: #007bff;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
}
.remove-button {
  padding: 4px 8px;
  background-color: orange;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
}
.list-button {
  padding: 4px 8px;
  background-color: green;
  color: #fff;
  text-decoration: none;
  border-radius: 4px;
}
</style>

<script>
  const mp = new MercadoPago('TEST-2f87e803-eed9-4a59-90b7-c5a6ef6554f3');

  const securityCodeElement = mp.fields.create('securityCode', {
    placeholder: "CVV"
  }).mount('form-checkout__securityCode-container');

  const customerCards = <%= @cards.to_json.html_safe %>
  console.log(customerCards)

  function appendCardToSelect() {
    const selectElement = document.getElementById('form-checkout__cardId');
    const tmpFragment = document.createDocumentFragment();
    customerCards.forEach(({ id, last_four_digits, payment_method }) => {
      console.log(id, last_four_digits, payment_method)
      const optionElement = document.createElement('option');
      optionElement.setAttribute('value', id)
      optionElement.textContent = `${payment_method.name} finalizada en ${last_four_digits}`
      tmpFragment.appendChild(optionElement);
    })
    selectElement.appendChild(tmpFragment)
  }
  appendCardToSelect();

  const formElement = document.getElementById('form-checkout');
  formElement.addEventListener('submit', e => createCardToken(e));
  const createCardToken = async (event) => {
    try {
      const tokenElement = document.getElementById('token');
      if (!tokenElement.value) {
        event.preventDefault();
        const token = await mp.fields.createCardToken({
          cardId: document.getElementById('form-checkout__cardId').value
        });
        tokenElement.value = token.id;
        console.log(token.id);
        formElement.requestSubmit();
      }
    } catch (e) {
      console.error('error creating card token: ', e)
    }
  }
</script>

<style>
    #form-checkout {
      display: flex;
      flex-direction: column;
      max-width: 600px;
    }

    .container {
      height: 18px;
      display: inline-block;
      border: 1px solid rgb(118, 118, 118);
      border-radius: 2px;
      padding: 1px 2px;
    }
  </style>

app/views/subscriptions/new_card.html.erb
<!-- PaymentBrick -->

<div id="cardPaymentBrick_container"></div>

<script>
const mp = new MercadoPago('TEST-2f87e803-eed9-4a59-90b7-c5a6ef6554f3', {
  locale: 'es'
});
const bricksBuilder = mp.bricks();

const renderCardPaymentBrick = async (bricksBuilder) => {
  const settings = {
    initialization: {
      amount: 100, // total amount to be paid
      payer: {
        email: "marca@gmail.com", // reemplazar por el email del usuario, evita solicitarlo en la vista
        customerId: '1666102147-Vr6jz04Pk43GS7',
        cardsIds: [ '1707009371209' ]
      },
    },
    customization: {
    visual: {
      style: {
        theme: "default",
      },
      texts: {
        formSubmit: "Guardar",
      },
    },
    paymentMethods: {
      creditCard: "all",
      debitCard: "all",
      bankTransfer: "all",
      onboarding_credits: "all",
      maxInstallments: 1
    },
  },
    callbacks: {
      onReady: () => {
        /*
          Callback called when Brick is ready.
          Here you can hide loadings from your site, for example.
        */
      },
      onSubmit: (formData) => {
        // callback called when clicking on the submit data button
        return new Promise((resolve, reject) => {
          fetch('/subscriptions/create_card', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify(formData),
          })
            .then((response) => response.json())
            .then((response) => {
              console.log(response);
              window.location.href = '/subscriptions';
              resolve();
            })
            .catch((error) => {
              console.log('errorx',error);
              reject();
            });
        });
      },
      onError: (error) => {
        // callback called for all Brick error cases
        console.error(error);
      },
    },
  };
  window.cardPaymentBrickController = await bricksBuilder.create(
    'cardPayment',
    'cardPaymentBrick_container',
    settings,
  );
};
renderCardPaymentBrick(bricksBuilder);

</script>

app/views/subscriptions/plans.html.erb
<%=@plans.to_json%>