config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"

  resources :sessions do
    get '/callback', to: 'sessions#callback',on: :collection
    get '/media', to: 'sessions#media',on: :collection
    get '/user', to: 'sessions#user',on: :collection
  end

  get '/instagram/callback', to: 'instagram#callback'
  post '/instagram/access', to: 'instagram#access'
  get '/instagram', to: 'instagram#index'
  get '/instagram/user_info', to: 'instagram#user_info'
  get '/instagram/user_insights', to: 'instagram#user_insights'
  get '/instagram/media_insights', to: 'instagram#media_insights'

  resources :tiktok, only: [:index] do
    get :research_token, on: :collection
    get :research_api, on: :collection
  end
  get '/auth/tiktok/login', to: 'tiktok#tiktok_auth'
  get '/auth/callback', to: 'tiktok#callback'


  resources :subscriptions, only: [:index, :create] do
    post :create_payment, on: :collection
    get :new_card, on: :collection
    post :create_card, on: :collection
    get :remove_cards, on: :collection
    get :list_payments, on: :collection
  end

  namespace :payment_gateway, path: 'pg' do
    resources :payment, only: [:create] do
      post :create_sub, on: :collection
    end
  end

  resources :culqi, only: [:index, :create]
end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController

  def callback
  end

  def access
    # obtener el long lived token
    short_lived_token = params[:access_token]
    oauth = Koala::Facebook::OAuth.new(ENV['INSTAGRAM_CLIENT_ID_GRAPH'], ENV['INSTAGRAM_CLIENT_SECRET_GRAPH'])
    new_access_info = oauth.exchange_access_token_info(short_lived_token)
    long_lived_token = new_access_info["access_token"]
    expires_at = DateTime.now + new_access_info["expires_in"].to_i.seconds
    session[:access_token_graph] = long_lived_token

    # obtener el primer instagram account por ahora
    @graph = Koala::Facebook::API.new(long_lived_token)
    data = @graph.get_object('me/accounts', fields: 'instagram_business_account')
    insta_account = get_first_instagram_business_account_id(data)
    session[:insta_account] = insta_account
  end

  def index
    @access_token = session[:access_token_graph]
    @insta_account = session[:insta_account]
  end

  def user_info
    graph = Koala::Facebook::API.new(session[:access_token_graph])
    res = graph.get_object(session[:insta_account], fields: 'biography,id,ig_id,followers_count,follows_count,media_count,name,profile_picture_url,username,website')
    res["ir atrás"] = url_for(controller: 'instagram', action: 'index')
    render json: res
  end

# ?metric=engaged_audience_demographics&period=lifetime&metric_type=total_value&timeframe=last_90_days&breakdown=age
  def user_insights
    graph = Koala::Facebook::API.new(session[:access_token_graph])
    fields_user = 'id,name,username,profile_picture_url,biography,followers_count,follows_count,media_count,stories,
    insights.metric(impressions,reach).period(day)'
    fields_demo = 'insights.metric(impressions,reach).period(day)'
    fields_user_res = graph.get_object(session[:insta_account], { fields: fields_user })
    fields_demo_res = graph.get_object('17841462527107856/insights', {
      metric: 'engaged_audience_demographics',
      metric_type: 'total_value',
      period: 'lifetime',
      timeframe: 'last_30_days',
      breakdown: 'age'
    })
    x = fields_demo_res.unshift(fields_user_res)
    x << { 'ir atrás': url_for(controller: 'instagram', action: 'index') }
    render json: x
  end

  def media_insights
    graph = Koala::Facebook::API.new(session[:access_token_graph])
    fields = 'id,caption,media_type,media_url,permalink,thumbnail_url,like_count,comments_count,timestamp,
              comments{id,text,username,like_count,replies{id,username,like_count,text}},
              insights.metric(impressions,reach,comments,follows,likes,shares){name,period,description,values}'
    insights = graph.get_object("#{session[:insta_account]}/media", { fields: fields })
    insights << { 'ir atrás': url_for(controller: 'instagram', action: 'index') }
    render json: insights
  end

  private

  def get_first_instagram_business_account_id(data)
    data.each do |item|
      if item['instagram_business_account']
        return item['instagram_business_account']['id']
      end
    end
    nil
  end
end

app/views/instagram/callback.html.erb
<script>
$(document).ready(function() {
  var fragment = window.location.hash.substring(1);
  var params = new URLSearchParams(fragment);
  var access_token = params.get("access_token");

  var csrfToken = $('meta[name="csrf-token"]').attr('content');
  $.ajax({
    url: "/instagram/access",
    method: "POST",
    headers: {
      'X-CSRF-Token': csrfToken
    },
    data: { access_token: access_token },
    success: function(response) {
      window.location.href = "/instagram";
    }
  });
});
</script>

app/views/instagram/index.html.erb
<% if @access_token %>
  <% if @insta_account %>
    <br>
    <%#= link_to 'user info', instagram_user_info_path %>
    <br>
    <br>
    <%= link_to 'user info/insights', instagram_user_insights_path %>
    <br>
    <br>
    <%= link_to 'media info/insights', instagram_media_insights_path %>
  <% else %>
    <p>No se encontró una cuenta de instagram</p>
  <% end %>
<% else %>
  <p>No hay access token</p>
<% end %>
<br>
<br>
<% link_to 'ir atrás', instagram_path %>
<br>
<br>
<% link_to 'inicio', new_session_path %>